---
apiVersion: v1
kind: Secret
metadata:
  name: kaniko-secret
stringData:
  config.json: |-
    {
      "auths": {
        "rabbitmqaldevopstest.azurecr.io": {
          "auth": "" # From docker config.json. Base64 encoded login:password string 
          }
        }       
    }
